Model\P2_EntitesRepositories\Subject:
  type: entity
  table: Subject
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    subject:
      type: string
      length: 64