Model\P2_EntitesRepositories\Teacher:
  type: entity
  table: Teacher
  id:
    teacherId:
      type: string
      length: 255
  fields:
    name:
      type: string
      length: 255
  oneToMany:
    subjectAssignments:
      targetEntity: Model\P2_EntitesRepositories\SubjectAssignment
      mappedBy: teacher
      cascade: [all]